// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.184
// </auto-generated>
// ------------------------------------------------------------------------------
namespace YarnTaskRunner
{
    static class Vsix
    {
        public const string Id = "2ff7da40-5096-441d-b8fc-17bc7e9255bc";
        public const string Name = "Yarn Task Runner";
        public const string Description = @"Adds support for yarn scripts defined in package.json directly in Visual Studio's Task Runner Explorer";
        public const string Language = "en-US";
        public const string Version = "0.1";
        public const string Author = "Miguel Alho";
        public const string Tags = "yarn, package.json, task runner, scripts";
    }
}
